name: tz
services:
# App 
  transaction-service:
    container_name: transaction-service
    build:
      context: ../..
      dockerfile: ./devops/dev/Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      # - ../../node_modules:/usr/src/app/node_modules
      - ../../src:/usr/src/app/src
      # - /usr/src/app/node_modules
    ports:
      - "3004"
    environment:
      NODE_ENV: development
    command: npm run start:dev